<a href="https://colab.research.google.com/github/reyonecy/ml_from_scratch1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to NumPy.

What will we cover?
- creating arrays
- Multi dimensional arrays
- Randomly generated arrays
- Element wis operations
  - Comparison operations
  - Logical Operations
- Summarizing operations

In [2]:
import numpy as np

## Single Dimension arrays

In [6]:
var = np.zeros(5)
print(type(var))

<class 'numpy.ndarray'>


In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [14]:
new = np.array([1, 2, 3, 4])
new[2] = 5
print(new)

[1 2 5 4]


In [15]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

- Create arrays with evenly spaced numbers within a specified range .**bold text**

In [17]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Multidimension Arrays

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

- create an MD unit Array of size (5, 2)
- Generate a random array of size (3, 5) with elements of your choice
- update the element of an array with index

In [21]:


    # create an MD unit Array of size (5, 2)
    # Generate a random array of size (3, 5) with elements of your choice
   # update the element of an array with index



In [26]:
multi = np.array([[1, 2, 3],[4, 5 , 6],[7, 8, 9]])
print(type(multi))

<class 'numpy.ndarray'>


In [27]:
multi[2] =[2, 2, 2]
multi

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 2]])

In [28]:
multi[:, 2] = [3, 3, 3]

## Randomly generated arrays

- Numpy can create arrays filled with random numbers.
- To ensure the reproducibility, you can set a seed using np.random.seed()
- Everytime you can run the code with np.random.seed(2), it will generate the exact same random numbers.
If you remove or change the seed values, the sequence of random numbers will be changed *italicized text*

In [37]:
np.random.seed(2)
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [46]:
np.random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [50]:
np.random.randn(5, 2)  #means value 0 and  standard deviation 1

array([[-0.08687561,  1.56153229],
       [-0.30585302, -0.47773142],
       [ 0.10073819,  0.35543847],
       [ 0.26961241,  1.29196338],
       [ 1.13934298,  0.4944404 ]])

In [52]:
np.random.seed(42)
np.random.randint(low =0, high=100, size=(5,2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

## Element wise operations

In [53]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [54]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [55]:
# Comparison operations
# You can perform element -wise comparison and create boolean arrays
a

array([0, 1, 2, 3, 4])

In [56]:
a>= 2

array([False, False,  True,  True,  True])

In [57]:
a > b

array([False, False, False, False, False])

In [58]:
# Summarizing
# Numpy provides functions for summarizing array of date
a

array([0, 1, 2, 3, 4])

In [59]:
# standard deviation
a.std()

1.4142135623730951

In [60]:
# Minimun value of an array
a.max()

4

In [61]:
# Sum of the elements of an array
a.sum(

)

10

In [63]:
# Mean value of an array
a.mean()

2.0